export const NEW_CATBANER_REQUEST = "NEW_CATBANER_REQUEST";
export const NEW_CATBANER_SUCCESS = "NEW_CATBANER_SUCCESS";
export const NEW_CATBANER_FAIL = "NEW_CATBANER_FAIL";
export const NEW_CATBANER_RESET = "NEW_CATBANER_RESET";

export const DELETE_CATBANER_REQUEST = "DELETE_CATBANER_REQUEST";
export const DELETE_CATBANER_SUCCESS = "DELETE_CATBANER_SUCCESS";
export const DELETE_CATBANER_FAIL = "DELETE_CATBANER_FAIL";
export const DELETE_CATBANER_RESET = "DELETE_CATBANER_RESET";

export const ALL_CATBANER_REQUEST = "ALL_CATBANER_REQUEST";
export const ALL_CATBANER_SUCCESS = "ALL_CATBANER_SUCCESS";
export const ALL_CATBANER_FAIL = "ALL_CATBANER_FAIL";

export const CAT_BANER_DETAILS_REQUEST = "CAT_BANER_DETAILS_REQUEST";
export const CAT_BANER_DETAILS_SUCCESS = "CAT_BANER_DETAILS_SUCCESS";
export const CAT_BANER_DETAILS_FAIL = "CAT_BANER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
