export const GET_RAZORPAY_KEY_REQUEST = "GET_RAZORPAY_KEY_REQUEST";
export const GET_RAZORPAY_KEY_SUCCESS = "GET_RAZORPAY_KEY_SUCCESS";
export const GET_RAZORPAY_KEY_FAIL = "GET_RAZORPAY_KEY_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
