export const ALL_SHOPS_REQUEST = "ALL_SHOPS_REQUEST";
export const ALL_SHOPS_SUCCESS = "ALL_SHOPS_SUCCESS";
export const ALL_SHOPS_FAIL = "ALL_SHOPS_FAIL";

export const SHOP_DETAILS_REQUEST = "SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS = "SHOP_DETAILS_SUCCESS";
export const SHOP_DETAILS_FAIL = "SHOP_DETAILS_FAIL";

export const NEW_SHOP_REQUEST = "NEW_SHOP_REQUEST";
export const NEW_SHOP_SUCCESS = "NEW_SHOP_SUCCESS";
export const NEW_SHOP_FAIL = "NEW_SHOP_FAIL";

export const GET_SHOP_PRODUCTS_REQUEST = "GET_SHOP_PRODUCTS_REQUEST";
export const GET_SHOP_PRODUCTS_SUCCESS = "GET_SHOP_PRODUCTS_SUCCESS";
export const GET_SHOP_PRODUCTS_FAIL = "GET_SHOP_PRODUCTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
